apiVersion: app-spec.ai/v0.1
kind: App

metadata:
  name: hello-world
  version: 0.1.0
  description: A minimal AI app that greets the user.

spec:
  entrypoint: greeter
  resources:
    - id: greeter
      type: agent
      implementation:
        format: example.app-spec.ai/text-agent:v1
        package:
          location: ./packages/greeter.txt
          digest: sha256:57ed92edff67e804cb81d661af4c3b7cd33bfdb72af9a63ac7cc456322d04e6e
